export const SYSTEM_CATEGORIES = [
  {
    name: 'Food',
    isIncome: false,
    icon: '🍔',
    subcategories: ['Groceries', 'Eating Out', 'Café', 'Alcohol', 'Delivery'],
  },
  {
    name: 'Transport',
    isIncome: false,
    icon: '🚗',
    subcategories: [
      'Gas',
      'Parking',
      'Transit',
      'Bike Share',
      'Rideshare',
      'Car Rental',
      'Car Maintenance',
      'Car Insurance',
      'Car Wash',
      'Registration & Licensing',
    ],
  },
  {
    name: 'Shopping',
    isIncome: false,
    icon: '🛍️',
    subcategories: ['Clothing', 'Online Retail', 'Electronics', 'Other'],
  },
  {
    name: 'Health',
    isIncome: false,
    icon: '💊',
    subcategories: [
      'Pharmacy',
      'Medical',
      'Dental',
      'Vision',
      'Gym & Fitness',
      'Yoga & Pilates',
      'Supplements',
      'Therapy & Mental Health',
    ],
  },
  {
    name: 'Entertainment',
    isIncome: false,
    icon: '🎮',
    subcategories: [
      'Gaming',
      'Streaming',
      'Events',
      'Sports',
      'Books & Reading',
    ],
  },
  {
    name: 'Housing',
    isIncome: false,
    icon: '🏠',
    subcategories: [
      'Rent',
      'Utilities',
      'Internet',
      'Phone & Mobile',
      'Home Insurance',
      'Property Tax',
      'Furniture',
      'Repairs',
      'Cleaning Supplies',
    ],
  },
  {
    name: 'Personal Care',
    isIncome: false,
    icon: '🪥',
    subcategories: ['Haircut', 'Skincare', 'Cosmetics', 'Spa & Wellness'],
  },
  {
    name: 'Travel',
    isIncome: false,
    icon: '✈️',
    subcategories: [
      'Flight',
      'Accommodation',
      'Car Rental',
      'Activities',
      'Dining',
      'Travel Insurance',
    ],
  },
  {
    name: 'Subscriptions',
    isIncome: false,
    icon: '🔁',
    subcategories: ['Software', 'Media', 'Services'],
  },
  {
    name: 'Education',
    isIncome: false,
    icon: '📚',
    subcategories: [
      'Tuition',
      'Courses',
      'Books',
      'Supplies',
      'Student Loan Interest',
    ],
  },
  {
    name: 'Finance',
    isIncome: false,
    icon: '💳',
    subcategories: [
      'Bank Fees',
      'Interest Charges',
      'Insurance',
      'Tax Payment',
      'Accountant',
    ],
  },
  {
    name: 'Gifts & Giving',
    isIncome: false,
    icon: '🎁',
    subcategories: ['Gifts', 'Charitable Donations'],
  },
  {
    name: 'Miscellaneous',
    isIncome: false,
    icon: '📦',
    subcategories: ['Other'],
  },
  {
    name: 'Salary',
    isIncome: true,
    icon: '💰',
    subcategories: ['Paycheque', 'Bonus', 'Severance', 'Freelance & Contract'],
  },
  {
    name: 'Government',
    isIncome: true,
    icon: '🏛️',
    subcategories: ['Tax Refund', 'GST Credit', 'Benefits', 'EI'],
  },
  {
    name: 'Investments',
    isIncome: true,
    icon: '📈',
    subcategories: ['Dividends', 'Capital Gains', 'Interest'],
  },
  {
    name: 'Other Income',
    isIncome: true,
    icon: '💵',
    subcategories: [
      'Side Hustle',
      'Rental Income',
      'Reimbursement',
      'Gift Received',
      'Misc',
    ],
  },
  {
    name: 'Transfer',
    isIncome: false,
    icon: '↔️',
    subcategories: [
      'Personal Transfer',
      'Credit Card Payment',
      'TFSA Contribution',
      'RRSP Contribution',
      'FHSA Contribution',
    ],
  },
];
